# Define our stages
stages:
  - build
  - lint

# Define the build stage
build:
  stage: build
  image: golang:1.16
  script:
    - go build -v -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/developer-bot ./main.go
  artifacts:
    paths:
      - developer-bot

# Define the linting stage
lint:
  stage: lint
  image: golangci/golangci-lint:v1.39-alpine
  script:
    - golangci-lint run -v

