# Define our stages
stages:
  - build
  - lint

# Define the build stage
# FIXME: alpine based golang images gives error here, but not in Dockerfile. WTF?
# NOTE:  One diff is -race
build:
  stage: build
  image: golang:1.16
  script:
    - go build -v -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/developer-bot ./main.go

# Define the linting stage
lint:
  stage: lint
  image: golangci/golangci-lint:v1.39-alpine
  script:
    - golangci-lint run -v

