version: "3.9"

services:
  developer-bot:
    build: .
    ports:
      - 8080:80
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/service-account-key
    secrets:
      - service-account-key

secrets:
  service-account-key:
    file: ./service-account-key.json
